### ISSUE TITLE
What does tfrecord_58parts_complete directory containe?

### ISSUE THREAD

**Issue by Njuod** [LTTM/GMNet#1]
Hi Umberto,

Thank you for sharing your code.

I'm trying to perform training but I've gotten an error which I think related to the dataset directory. So, could you clarify what tfrecord_58parts_complete should contain?

`python -u train.py
--logtostderr
--train_split train
--model_variant resnet_v1_101_beta
--atrous_rates 6
--atrous_rates 12
--atrous_rates 18
--output_stride 16
--decoder_output_stride 4
--train_crop_size "513,513"
--base_learning_rate 0.005
--train_batch_size 10
--training_number_of_steps 50000
--dataset pascal_voc_seg_58_parts
--tf_initial_checkpoint pretrained/imagenet/resnet_v1_101_2018_05_04/model.ckpt
--train_logdir TRAIN_58_parts
--dataset_dir tfrecord_58parts_complete
--model_softmax 1
--graph_loss 1
--weighted_graph 1
--class_dilation_kernel 2
--graph_lambda_loss 0.1
--graph_loss_type 'mean_squared_error'
--aux_loss 1
--aux_lambda_loss 0.0001
1> TRAIN_58_parts.txt 2>&1`

When I set the dataset_dir to tfrecord_58_parts I get the following error:

`INFO:tensorflow:Starting Queues.
INFO:tensorflow:Error reported to Coordinator: Expected image (JPEG, PNG, or GIF), got empty file
	 [[{{node cond_2/DecodePng}}]]
	 [[node IteratorGetNext (defined at deeplab/train.py:481) ]]
	 [[node while_1/while/SparseToDense (defined at /home/usr/models/GMNet/GMNet-master/Deeplab/research/deeplab/utils/train_utils.py:115) ]]`

**Comment by umbertomichieli** [comment]
Hi, thank you for your interest in our work.
Unfortunately, I found that there is a bug in the generation of the tfrecords. As a temporary workaround you can download all the tfrecords needed from [here](https://drive.google.com/drive/u/4/folders/193qJXouWxtlmp4nU3TgqanRdR_-WqX5h) (as I just specified in the README). So you can skip all the first part and go directly to evaluation or training.
Sorry for the inconvenience.

**Comment by Njuod** [comment]
Great! thank you for providing all the tfrecords.

To visualize the part-level predictions, could you clarify how we can obtain tfrecord_58parts_softmax?

`python -u vis_parts.py
--logtostderr
--eval_split val
--model_variant resnet_v1_101_beta
--atrous_rates 6
--atrous_rates 12
--atrous_rates 18
--output_stride 16
--decoder_output_stride 4
--eval_crop_size "513,513"
--checkpoint_dir TRAIN_58_parts
--vis_logdir VIS_58_parts
--dataset pascal_voc_seg_58_parts
--dataset_dir tfrecord_58parts_softmax
--max_number_of_evaluations 1
--model_softmax 1 `

Your help is much appreciated.

**Comment by umbertomichieli** [comment]
HI, you can place there the tfrecords provided.
If you **only** want to see the predictions you can also find them in the zip file provided in the description: https://lttm.dei.unipd.it/paper_data/GMNet/data.zip

Kind Regards

**Comment by Njuod** [comment]
Thanks!
Using tfrecord_58parts_complete solved it.

**Comment by Njuod** [comment]
Hi Umberto, hope you're okay.

I am wondering about the large size of part-level tfrecords, as each file is approximately 19GB, do you have an idea of the reason for that?
